version: '3.9'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount source code for live reload
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


